name: Precommit Check

on: [push, pull_request]
jobs:
  precommit-check:
    runs-on: ubuntu-latest
    outputs:
      pass-value: ${{ steps.result.outputs.result }}
      fail-value: "1"
      branch-name: "${GITHUB_REF}"
      current-user: "${GITHUB_ACTOR}"
      commit-sha: "${GITHUB_SHA}"

    steps:
      - uses: actions/checkout@v2

      - name: precommit-check
        # run precommit script
        id: result
        run: echo "::set-output name=result${GITHUB_WORKSPACE}/.git-hooks/pre-commit.sh"
        shell: bash
        with: 
          password: ${{ secrets.ACCESS_TOKEN }}

  # precommit-failed:
  #   runs-on: ubuntu-latest
  #   needs: precommit-check
  #   if: needs.precommit-check.outputs.fail-value
  #   steps:
  #     - run: echo "${GITHUB_ACTOR} did not pass the checks"
  #     - run: git reset

  # precommit-passed:
  #   runs-on: ubuntu-latest
  #   needs: precommit-check
  #   if: needs.precommit-check.outputs.pass-value
  #   steps:
  #     - run: echo "${GITHUB_ACTOR} has successfully passed the checks"

      
      # - name: precommit-failed
      #   run: 
      #   with:
      #     job-status: ${{ precommit-check.status }}
        

      # - name: precommit-passed